import { Props } from "../components/Reviewer/ReviewerCard";

export const reviewers: Props[] = [
  {
    id: 1,
    avatarUrl: "https://avatars.githubusercontent.com/u/52202474?v=4",
    career: 3,
    reviewCount: 1,
    averageResponseTime: 10,
    title: "안녕하세요~브랜입니다. 타입스크립트 정말 잘해용 믿고 맡겨주세요.",
    languages: ["JavaScript", "Java"],
    skills: ["React", "Angular"],
  },
  {
    id: 2,
    avatarUrl: "https://avatars.githubusercontent.com/u/67591151?v=4",
    career: 30,
    reviewCount: 777,
    averageResponseTime: 100,
    title: "안녕하세요~신세한탄입니당~",
    languages: ["C#", "English"],
    skills: ["React", "Music"],
  },
  {
    id: 3,
    avatarUrl: "https://avatars.githubusercontent.com/u/50273712?s=88&u=759d7139f199c18bb79acc7cf9589e188f92c5ea&v=4",
    career: 10,
    reviewCount: 3,
    averageResponseTime: 1,
    title: "안녕하세요~ 파피입니다~ 피파잘해요~",
    languages: ["JavaScript", "Java"],
    skills: ["FIFA_ONLINE3", "Spring"],
  },
  {
    id: 4,
    avatarUrl: "https://avatars.githubusercontent.com/u/45876793?s=88&u=4be72d288d3fb307031fb2a5f0164eef7b116e5d&v=4",
    career: 11,
    reviewCount: 22,
    averageResponseTime: 11,
    title: "안녕하세요~ 에어입니당 농구잘해용^^",
    languages: ["Go", "Scala"],
    skills: ["BasketBall"],
  },
  {
    id: 5,
    avatarUrl: "https://avatars.githubusercontent.com/u/56301069?v=4",
    career: 80,
    reviewCount: 10007,
    averageResponseTime: 0.1,
    title: "안녕하세요~ 시드입니다~ featrue~~~",
    languages: ["Korean", "Java"],
    skills: ["React", "Angular"],
  },
  {
    id: 6,
    avatarUrl: "https://avatars.githubusercontent.com/u/32974201?v=4",
    career: 3,
    reviewCount: 300,
    averageResponseTime: 1,
    title: "안녕하세요~ 알리입니다~ 인프라는 저에게 맡겨주세욤",
    languages: ["JavaScript", "Java"],
    skills: ["Infra", "Angular"],
  },
];
